apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
  namespace: $NAMESPACE
  labels:
    app: $K8S_CONTAINER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $K8S_CONTAINER
  template:
    metadata:
      labels:
        app: $K8S_CONTAINER
    spec:
      containers:
        - name: $K8S_CONTAINER
          image: $ECR_REPO_URI/$AWS_ECR_REPOSITORY:$IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: $PORT
          resources:
            requests:
              cpu: $REQUEST_CPU
              memory: $REQUEST_MEM
              ephemeral-storage: $REQUEST_EPM
            limits:
              cpu: $LIMIT_CPU
              memory: $LIMIT_MEM
              ephemeral-storage: $LIMIT_EPM

---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
  labels:
    app: $K8S_CONTAINER
spec:
  type: ClusterIP
  selector:
    app: $K8S_CONTAINER
  ports:
    - port: $PORT
      targetPort: $PORT

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: $HPA_NAME
  namespace: $NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $DEPLOYMENT_NAME
  minReplicas: 1
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 120
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
   - type: Resource
     resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 70
